### ISSUE TITLE
admin side features

### ISSUE THREAD

**Issue by Marc-pi** [pi-module/message#11]
* display in message module admin the list of ALL messages order by creation date D with pagination and filter per account

* Admin must be able to read them and count per customer if how many messages are shared. 

* prune feature : all before xxxx

* add a feature to send a message to ALL users or seleted groups or one user

**Comment by voltan** [comment]
List of message added

**Comment by Marc-pi** [comment]
i get an error on accessing to module on admin side to see the list of messages
admin/message/list/ get blank page

**Comment by voltan** [comment]
I am at check , here work whitout problem, please remove old files and update new files again and update module to last version

**Comment by Marc-pi** [comment]
still ko here on prod (1.0.2)

**Comment by voltan** [comment]
can you please re install module? here work true

**Comment by Marc-pi** [comment]
yep, i've uninstalled and reinstalled, works now (i lost some messages, but better to have a working module than to loose time)

**Comment by Marc-pi** [comment]
> display in message module admin the list of ALL messages order by creation date D with pagination and filter per account
* Admin must be able to read them and count per customer if how many messages are shared.
*  add a feature to send a message to ALL users or seleted groups or one user

**Comment by voltan** [comment]
You need it on this 2 3 weeks? I think we can wait for this part
