### ISSUE TITLE
UI user side

### ISSUE THREAD

**Issue by Marc-pi** [pi-module/message#12]
* improve message UI : thread, make more readable sender/reader's messages, keep one dedicated background color for unread messages

**Comment by voltan** [comment]
Check ui

**Comment by Marc-pi** [comment]
Little bug /UX mistake 
* avatar must be displayed aside who wrote the text in every case, with AccountName(username i guess) : here it is absent in this case, despite i have one set
* avatar name must be displayed : `Me` if it's me, other user AccountName (username i guess)
* `To Me` or `To AccountName` must be displayed at the start of the message

![sendermessage](https://cloud.githubusercontent.com/assets/919332/10493029/2ef30caa-72af-11e5-8283-d37ef1601c4c.JPG)

* issue with avatar : when zooming into message, it's here displayed (it was not on Message index), but it is blured !
![blured](https://cloud.githubusercontent.com/assets/919332/10493062/64a6da20-72af-11e5-95ec-1b6b27753473.JPG)


* When zooming in to read the message, the whole thread must be displayed above, so user remind what it was about

**Comment by Marc-pi** [comment]
i'll test after those fix with a new interaction between users, to see the colors you used for unread.
we need to display unread on the left menu and top bar (guide module).

**Comment by Marc-pi** [comment]
you can also use a circular avatar ! better look&fell IMHO

**Comment by voltan** [comment]
For better test , please make new user and send message whit that account , than you see avatar work true , keep this message too . 

this problem is , you send message for your self

**Comment by Marc-pi** [comment]
"this problem is , you send message for your self , i fix user name" : NOOOOO, i created a new account

**Comment by voltan** [comment]
Ok , I will check

**Comment by Marc-pi** [comment]
* my avatar still not displayed
* rounded avatar can be better
* background color yellow : strange, what does this color correspond to? i've One message from Me and One message To Me. 
![message2](https://cloud.githubusercontent.com/assets/919332/10493837/8c8e16f8-72b3-11e5-9bb3-578e8e923958.JPG)

**Comment by voltan** [comment]
I add some fix here , you can see shot from two users and send message together 
![snapshot9](https://cloud.githubusercontent.com/assets/562083/10549249/d0d6cde2-744c-11e5-9bc0-312ffd8fc202.png)
![snapshot8](https://cloud.githubusercontent.com/assets/562083/10549248/d0bc8720-744c-11e5-8ea0-1393d28845b4.png)

**Comment by Marc-pi** [comment]
no, still ko
in every case, in sender message box, To and From Account displays always the same avatar : the To Account avatar ! 
in front of each message, the SENDER avatar must be displayed.

**Comment by voltan** [comment]
Check again

**Comment by Marc-pi** [comment]
several points fixed, except those

>
* When zooming in to read the message, the whole thread must be displayed above, so user remind what it was about
* mass operation do not work (and the checkbox is not on the left, like on gmail, you moved it aside the author link)
* we need to display unread on the left menu and top bar (guide module)

**Comment by voltan** [comment]
I add some changes on templates , for message count do this changes : https://github.com/voltan/pi/commit/5c59f85aa6f9ade9af042efeaf49a033b2b5f8b7

I can not understand this : `When zooming in to read the message, the whole thread must be displayed above, so user remind what it was about`

**Comment by Marc-pi** [comment]
when user zoom on a message to read it, we have to display the previous messages if any (nested messages)
ex : user discuss through message module
*  USER 1 sends a Message 1, 
* USER 2 answers through Message 2 
* => USER 1 when reading the detail of the Message 2 must see Message 1, message 2 and can then answer correctly, reading the whole thread.

**Comment by voltan** [comment]
I do not see any field than we can get this out put from that , ignore it from this issues , is not easy job , I will think about it

**Comment by Marc-pi** [comment]
still ko

> mass operation do not work (and the checkbox is not on the left, like on gmail, you moved it aside the author link)

**Comment by Marc-pi** [comment]
* discussion thread : ok, just fix a wording ( Content is displayed, must be Answer, and put it on the left with Answer to xxx)
![repondre](https://cloud.githubusercontent.com/assets/919332/11091100/b6c7cba6-8877-11e5-9b7e-616f12fbcb01.JPG)

* mass operation still do not work (and the checkbox is not on the left, like on gmail, you moved it aside the author link), 
* archive feature does not work either (there is no more the Archive option in the Mass Operation Selector)
* deletion : no confirmation message "Are you sure you want to delete this message?"
* we need to display unread on the left menu and top bar (guide module)
* replied message : we need an icon or indication for that, so user sees what post he replied already and that there is a thread behind. Here is an example, but if you have better idea...
![thread](https://cloud.githubusercontent.com/assets/919332/11091305/623093d2-8879-11e5-8fb5-d57e7587085b.JPG)

**Comment by Marc-pi** [comment]
up

**Comment by voltan** [comment]
Some parts of here fixed too.

**Comment by voltan** [comment]
> archive feature does not work either (there is no more the Archive option in the Mass Operation Selector)

I don't know what is this , I think about removed it , not see any code for this part

> we need to display unread on the left menu and top bar (guide module)

It added now , work form you?

**Comment by Marc-pi** [comment]
* discussion thread : content still displayed, must be Answer
![contentstilldisplayed](https://cloud.githubusercontent.com/assets/919332/11319242/96d29ad2-9070-11e5-9be0-42992fedc1ed.JPG)
* checkbox on the left : ok
* mass operation still do not work (it worked before our changes) : still ko
* archive still do not work (it worked before our changes) : still ko
* deletion : no confirmation message "Are you sure you want to delete this message?" : still not there
* we need to display unread on the left menu and top bar (guide module) : still ko (see user dashboard, must be visible on the left menu and top menu and frontpage)
* replied message : still ko. we need an icon or indication for that, so user sees what post he replied already and that there is a thread behind. Here is an example, but if you have better idea...
![thread](https://cloud.githubusercontent.com/assets/919332/11091305/623093d2-8879-11e5-8fb5-d57e7587085b.JPG)
* replied message : you do not see any answer on a thread. latest message must be displayed in message list, but if you click you must see the whole thread

**Comment by Marc-pi** [comment]
up !
and as said above, don't kill the archive, needed to keep trace for a Owner about the answer he gave and messages he managed (imagine a customer confirmed, he has to keep trace of his renting confirmation, to manage the litigation).

**Comment by voltan** [comment]
No archive exist on message module , just empty page 

> archive still do not work (it worked before our changes) : still ko

No coding for archive writed before by all module developers . 

-----------------------------------------------------------------------------------------------

Now , module work good for usages , I will back on it next weeks , after finish your needs on guid module and update some other needed on other modules
