### ISSUE TITLE
Hide/Delete messages

### ISSUE THREAD

**Issue by Marc-pi** [pi-module/message#13]
* User can delete their messages BUT the messages must be kept in DB with an access only to Admin  (for legal reason, and for giving to customers stats about how many reach they get through our platform).
* Admin can prune messages in DB : only hidden messages, all messages, by date (all messages before xxxx)

**Comment by voltan** [comment]
> User can delete their messages BUT the messages must be kept in DB with an access only to Admin 

At this moment all message after delete , stay keep on DB , just need show list of them on admin side on https://github.com/pi-module/message/issues/11

**Comment by Marc-pi** [comment]
> At this moment all message after delete , stay keep on DB , just need show list of them on admin side on #11

good ! i saw the prune feature
