### ISSUE TITLE
Return carriage

### ISSUE THREAD

**Issue by Marc-pi** [pi-module/message#16]
not taken into account
example : send this text through message module, return to new line not taken into account, and line break (blank line)

`
Une double planche du "Sceptre d'Ottokar", un album des aventures de Tintin par Hergé, a été adjugée près de 1,6 million d'euros samedi à Paris, "un record mondial pour une double planche originale de l'artiste", selon la maison d'enchères Sotheby's.

Cette double planche de Hergé, qui a atteint le double de son estimation haute, était la pièce phare de la collection de BD du Belge Jean-Arnold Schoofs, l'une des plus importantes au monde.

Parue dans Le Petit Vingtième en 1939 et montrant l'avion de Tintin qui amorce une chute vertigineuse, la planche du "Sceptre d'Ottokar", estimée entre 600.000 et 800.000 euros, a été disputée par quatre enchérisseurs jusqu'à 1,563 million d'euros. 
`

**Comment by Marc-pi** [comment]
@voltan , still ko

**Comment by Marc-pi** [comment]
up

**Comment by voltan** [comment]
I can not understand your problem

**Comment by Marc-pi** [comment]
read again first post
blank lines and return carriage are suppressed when posting. must be kept

**Comment by voltan** [comment]
this part should be fix

**Comment by Marc-pi** [comment]
still ko

**Comment by Marc-pi** [comment]
ok, works now
