### ISSUE TITLE
notification per email

### ISSUE THREAD

**Issue by Marc-pi** [pi-module/message#9]
* user do not receive any notification per mail, only on site. like Xoops, we need both, at best a selector to manage the way messages are send (online, mail, both).

i don't know the interaction between message and notification module

**Comment by voltan** [comment]
At this moment I set send mail notification , you need use last version of message module files and install notification module

**Comment by Marc-pi** [comment]
on notification, what does the cron make?

**Comment by voltan** [comment]
At this moment nothing

**Comment by Marc-pi** [comment]
About the notification text, we need this, to be consistent with other send messages (registration, change password, etc.)

````
Dear %username%,
You get new message on %site_name% website from %sender%. 
Please log into the site to check your messages. 
Don't reply to this email !
%site_name%
````

**Comment by voltan** [comment]
Check again
